### ISSUE TITLE
简体用户应该用t2s.json (t2s.json Traditional Chinese to Simplified Chinese 繁體到簡體)吧？谢谢！

### ISSUE THREAD

**Issue by zhuangzhemin** [shewer/librime-lua-script#8]
说明文档这里的"s2t.json   # 简体用户"和“t2s.json   # 繁体用户”是否写反了？
简体用户应该用t2s.json (t2s.json Traditional Chinese to Simplified Chinese 繁體到簡體)吧？谢谢！
```
# 请确认方案是否设定 simplifier
engine/filters:
  - simplifier
switches:
  - name: simplification
    states: [ 漢字,汉字 ]
simplifier/opencc_config: s2t.json   # 简体用户
simplifier/opencc_config: t2s.json   # 繁体用户  (預設值 可以不設)
```
